### ISSUE TITLE
toolStripMenuItemGyrAndAccCalibrationWizard toolStripMenuItemMagneticCalibrationWizard does not exist in the current context

### ISSUE THREAD

**Issue by paul-ferragut** [xioTechnologies/x-BIMU-Terminal#1]
in order to have the app compiling I commented 
toolStripMenuItemTools.DropDownItems.Remove(toolStripMenuItemGyrAndAccCalibrationWizard);
toolStripMenuItemTools.DropDownItems.Remove(toolStripMenuItemMagneticCalibrationWizard);

**Comment by xioTechnologies** [comment]
Thank you for pointing out this error.  The code as now been corrected to use the correct names "toolStripMenuItemGyroscopeAndAccelerometerCalibration" and "toolStripMenuItemMagneticCalibration" and now compiles.
